# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: |
      **/*.csproj
    arguments: --output publish_output --configuration Release

- script: cd Awemedia.Admin.AzureFunctions
  displayName: current folder

- script: dir
  displayName: List files

# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
#     includeRootFolder: false
#     archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#     replaceExistingArchive: true

- publish: $(System.DefaultWorkingDirectory)/publish_output
  artifact: drop
