using Awemedia.Admin.AzureFunctions.DAL.DataContracts;
using System;
using System.Collections.Generic;
using System.Text;

namespace Awemedia.Admin.AzureFunctions.DAL.Common
{
    public static class Constants
    {
        public static Dictionary<int, string> sessionTypes = new Dictionary<int, string>
        {
                { 1,"Promotion" },
                { 2,"Paid"  },
        };
        public static Dictionary<int, string> sessionStatuses = new Dictionary<int, string>
        {
               { 1,"New" },
                { 2,"AuthorizationSuccessful"},
                { 3,"AuthorizationFailure"},
                { 4,"PaymentRequestSent"},
                { 5,"PaymentCompleted"},
                { 6,"PaymentFailure"},
                { 7,"PaymentTimeout"},
                { 8,"PaymentCanceledByUser"},
                { 9,"Charging"},
                { 10,"ChargingCompleted"},
                { 11,"ChargeFailed"},
                { 12,"SessionTimeout"},
                { 13,"AuthorizationTimeout"},
                { 14,"PaymentRequestTimeout"},
                { 15,"ServerTimeOut"}
        };
        public static Dictionary<int, string> industryTypes = new Dictionary<int, string>
        {
                { 1,"F&b (food and beverage)"},
                { 2,"Karaoke" },
                { 3,"Service" },
                { 4,"Event"},
        };
        public static Dictionary<int, string> eventTypes = new Dictionary<int, string>
        {
                { 1,"app started"},
                { 2,"charge session started"},
                { 3,"charge session ended"},
                { 7,"charging session failed"},
                { 8,"charging station connection failed" },
                { 9,"charge station not returning the battery level"},
                { 12,"video started" },
                { 13,"video ended" },
                { 14,"video failed"},
                { 15,"battery command retried"},
                { 16,"charging command retried"},
                {17,"failed to get battery level after retring 5 times" },
                {18,"tablet disconnected" }
        };
        public static List<Tuple<int, string, string>> countries = new List<Tuple<int, string, string>>
{
        new Tuple<int, string,string>(1, "Albania" ,"ALL"),
        new Tuple<int, string,string>(2, "America" ,"USD"),
        new Tuple<int, string,string>(3, "Afghanistan" ,"AFN"),
        new Tuple<int, string,string>(4, "Argentina" ,"ARS"),
        new Tuple<int, string,string>(5, "Aruba" ,"AWG"),
        new Tuple<int, string,string>(6, "Australia" ,"AUD"),
        new Tuple<int, string,string>(7, "Azerbaijan" ,"AZN"),
        new Tuple<int, string,string>(8, "Bahamas" ,"BSD"),
        new Tuple<int, string,string>(9, "Barbados" ,"BBD"),
        new Tuple<int, string,string>(10, "Belarus" ,"BYR"),
        new Tuple<int, string,string>(11, "Belgium" ,"EUR"),
        new Tuple<int, string,string>(12, "Beliz" ,"BZD"),
        new Tuple<int, string,string>(13, "Bermuda" ,"BMD"),
        new Tuple<int, string,string>(14, "Bolivia" ,"BOB"),
        new Tuple<int, string,string>(15, "Bosnia and Herzegovina" ,"BAM"),
        new Tuple<int, string,string>(16, "Botswana" ,"BWP"),
        new Tuple<int, string,string>(17, "Bulgaria" ,"BGN"),
        new Tuple<int, string,string>(18, "Brazil" ,"BRL"),
        new Tuple<int, string,string>(19, "Britain (United Kingdom)" ,"GBP"),
        new Tuple<int, string,string>(20, "Brunei Darussalam" ,"BND"),
        new Tuple<int, string,string>(21, "Cambodia" ,"KHR"),
        new Tuple<int, string,string>(22, "Canada" ,"CAD"),
        new Tuple<int, string,string>(23, "Cayman Islands" ,"KYD"),
        new Tuple<int, string,string>(24, "Chile" ,"CLP"),
        new Tuple<int, string,string>(25, "China" ,"CNY"),
        new Tuple<int, string,string>(26, "Colombia" ,"COP"),
        new Tuple<int, string,string>(27, "Costa Rica" ,"CRC"),
        new Tuple<int, string,string>(28, "Croatia" ,"HRK"),
        new Tuple<int, string,string>(29, "Cuba" ,"CUP"),
        new Tuple<int, string,string>(30, "Cyprus" ,"EUR"),
        new Tuple<int, string,string>(31, "Czech Republic" ,"CZK"),
        new Tuple<int, string,string>(32, "Denmark" ,"DKK"),
         new Tuple<int, string,string>(33, "Dominican Republic" ,"DOP"),
        new Tuple<int, string,string>(34, "East Caribbean" ,"XCD"),
        new Tuple<int, string,string>(35, "Egypt" ,"EGP"),
        new Tuple<int, string,string>(36, "El Salvador" ,"SVC"),
        new Tuple<int, string,string>(37, "England (United Kingdom)" ,"GBP"),
        new Tuple<int, string,string>(38, "Euro" ,"EUR"),
        new Tuple<int, string,string>(39, "Falkland Islands" ,"FKP"),
        new Tuple<int, string,string>(40, "Fiji" ,"FJD"),
        new Tuple<int, string,string>(41, "France" ,"EUR"),
        new Tuple<int, string,string>(42, "Ghana" ,"GHC"),
         new Tuple<int, string,string>(43, "Gibraltar" ,"GIP"),
        new Tuple<int, string,string>(44, "Greece" ,"EUR"),
        new Tuple<int, string,string>(45, "Guatemala" ,"GTQ"),
        new Tuple<int, string,string>(46, "Guernsey" ,"GGP"),
        new Tuple<int, string,string>(47, "Guyana" ,"GYD"),
        new Tuple<int, string,string>(48, "Holland (Netherlands)" ,"EUR"),
        new Tuple<int, string,string>(49, "Honduras" ,"HNL"),
        new Tuple<int, string,string>(50, "Hong Kong" ,"HKD"),
        new Tuple<int, string,string>(51, "Hungary" ,"HUF"),
        new Tuple<int, string,string>(52, "Iceland" ,"ISK"),
        new Tuple<int, string,string>(53, "India" ,"INR"),
        new Tuple<int, string,string>(54, "Indonesia" ,"IDR"),
        new Tuple<int, string,string>(55, "Iran" ,"IRR"),
        new Tuple<int, string,string>(56, "Ireland" ,"EUR"),
        new Tuple<int, string,string>(57, "Isle of Man" ,"IMP"),
        new Tuple<int, string,string>(58, "Israel" ,"ILS"),
        new Tuple<int, string,string>(59, "Italy" ,"EUR"),
        new Tuple<int, string,string>(60, "Jamaica" ,"JMD"),
        new Tuple<int, string,string>(61, "Japan" ,"JPY"),
        new Tuple<int, string,string>(62, "Jersey" ,"JEP"),
        new Tuple<int, string,string>(63, "Kazakhstan" ,"KZT"),
        new Tuple<int, string,string>(64, "Korea (North)" ,"KPW"),
        new Tuple<int, string,string>(65, "Korea (South)" ,"KRW"),
        new Tuple<int, string,string>(66, "Kyrgyzstan" ,"KGS"),
        new Tuple<int, string,string>(67, "Laos" ,"LAK"),
        new Tuple<int, string,string>(68, "Latvia" ,"LVL"),
        new Tuple<int, string,string>(69, "Lebanon" ,"LBP"),
        new Tuple<int, string,string>(70, "Liberia" ,"LRD"),
        new Tuple<int, string,string>(71, "Liechtenstein" ,"CHF"),
        new Tuple<int, string,string>(72, "Lithuania" ,"LTL"),
        new Tuple<int, string,string>(73, "Luxembourg" ,"EUR"),
        new Tuple<int, string,string>(74, "Macedonia" ,"MKD"),
        new Tuple<int, string,string>(75, "Malaysia" ,"MYR"),
        new Tuple<int, string,string>(76, "Malta" ,"EUR"),
        new Tuple<int, string,string>(77, "Mauritius" ,"MUR"),
        new Tuple<int, string,string>(78, "Mexico" ,"MXN"),
        new Tuple<int, string,string>(79, "Mongolia" ,"MNT"),
        new Tuple<int, string,string>(80, "Mozambique" ,"MZN"),
        new Tuple<int, string,string>(81, "Namibia" ,"NAD"),
        new Tuple<int, string,string>(82, "Nepal" ,"NPR"),
         new Tuple<int, string,string>(83, "Netherlands Antilles" ,"ANG"),
        new Tuple<int, string,string>(84, "Netherlands" ,"EUR"),
        new Tuple<int, string,string>(85, "New Zealand" ,"NZD"),
        new Tuple<int, string,string>(86, "Nicaragua" ,"NIO"),
        new Tuple<int, string,string>(87, "Nigeria" ,"NGN"),
        new Tuple<int, string,string>(88, "North Korea" ,"KPW"),
        new Tuple<int, string,string>(89, "Norway" ,"NOK"),
        new Tuple<int, string,string>(90, "Oman" ,"OMR"),
        new Tuple<int, string,string>(91, "Pakistan" ,"PKR"),
        new Tuple<int, string,string>(92, "Panama" ,"PAB"),
        new Tuple<int, string,string>(93, "Paraguay" ,"PYG"),
        new Tuple<int, string,string>(94, "Peru" ,"PEN"),
        new Tuple<int, string,string>(95, "Philippines" ,"PHP"),
        new Tuple<int, string,string>(96, "Poland" ,"PLN"),
        new Tuple<int, string,string>(97, "Qatar" ,"QAR"),
        new Tuple<int, string,string>(98, "Romania" ,"RON"),
        new Tuple<int, string,string>(99, "Russia" ,"RUB"),
        new Tuple<int, string,string>(100, "Saint Helena" ,"SHP"),
        new Tuple<int, string,string>(101, "Saudi Arabia" ,"SAR"),
        new Tuple<int, string,string>(102, "Serbia" ,"RSD"),
        new Tuple<int, string,string>(103, "Seychelles" ,"SCR"),
        new Tuple<int, string,string>(104, "Singapore" ,"SGD"),
        new Tuple<int, string,string>(105, "Slovenia" ,"EUR"),
        new Tuple<int, string,string>(106, "Solomon Islands" ,"SBD"),
        new Tuple<int, string,string>(107, "Somalia" ,"SOS"),
        new Tuple<int, string,string>(108, "South Africa" ,"ZAR"),
        new Tuple<int, string,string>(109, "South Korea" ,"KRW"),
        new Tuple<int, string,string>(110, "Spain" ,"EUR"),
        new Tuple<int, string,string>(111, "Sri Lanka" ,"LKR"),
        new Tuple<int, string,string>(112, "Sweden" ,"SEK"),
         new Tuple<int, string,string>(113, "Switzerland" ,"CHF"),
        new Tuple<int, string,string>(114, "Suriname" ,"SRD"),
        new Tuple<int, string,string>(115, "Syria" ,"SYP"),
        new Tuple<int, string,string>(116, "Taiwan" ,"TWD"),
        new Tuple<int, string,string>(117, "Thailand" ,"THB"),
        new Tuple<int, string,string>(118, "Trinidad and Tobago" ,"TTD"),
        new Tuple<int, string,string>(119, "Turkey" ,"TRY"),
        new Tuple<int, string,string>(120, "Turkey" ,"TRL"),
        new Tuple<int, string,string>(121, "Tuvalu" ,"TVD"),
        new Tuple<int, string,string>(122, "Ukraine" ,"UAH"),
        new Tuple<int, string,string>(123, "United Kingdom" ,"GBP"),
        new Tuple<int, string,string>(124, "United States of America" ,"USD"),
        new Tuple<int, string,string>(125, "Uruguay" ,"UYU"),
        new Tuple<int, string,string>(126, "Uzbekistan" ,"UZS"),
        new Tuple<int, string,string>(127, "Vatican City" ,"EUR"),
        new Tuple<int, string,string>(128, "Venezuela" ,"VEF"),
        new Tuple<int, string,string>(129, "Vietnam" ,"VND"),
        new Tuple<int, string,string>(130, "Yemen" ,"YER"),
        new Tuple<int, string,string>(131, "Zimbabwe" ,"ZWD"),
        new Tuple<int, string,string>(132, "India" ,"INR")
};
    }
}
